### PR TITLE
JsDocs & Readme

### LINKED ISSUE #18: Finish JSDoc comments in source code

### PR DESCRIPTION
**Pull request by crobinson42**
Fixes #18
- [x] - `npm test` succeeds
- [x] - Code coverage does not decrease (if any source code was changed)
- [x] - Appropriate JSDoc comments were updated in source code (if applicable)
- [x] - Approprate changes to js-data.io docs have been suggested ("Suggest Edits" button)

### CODE REVIEW

**Review by jmdobry — APPROVED** [review]
Ready to merge?

**Comment by crobinson42** [comment]
Yeah, just don't want to forget to put up the guide/tutorials on http://www.js-data.io/v3.0/docs/js-data-express

**Comment by jmdobry** [comment]
I'll give you write access

**Comment by jmdobry** [comment]
Don't break anything

**Pull request merged**
