### PR TITLE
update README

### PR DESCRIPTION
**Pull request by crobinson42**
Update README.md

### CODE REVIEW

**Comment by crobinson42** [comment]
@jmdobry @ramirezd42 Checkout the README and let me know thoughts and suggestions https://github.com/js-data/js-data-express/tree/docs

**Comment by jmdobry** [comment]
Can we just include the `tldr;` section in the readme and move the rest of the examples/guide-like stuff to http://www.js-data.io/v3.0/docs/js-data-express? Or if you don't mind duplicating content and keeping content between the two pages in sync. Also keep in mind that there is: http://api.js-data.io/js-data-express/latest/index.html

**Comment by crobinson42** [comment]
Sure thing. Where do those two pages populate from? What's the flow/procedure to update?

**Comment by jmdobry** [comment]
For the API docs (gh-pages):
1. `rm -rf doc`
2. `npm run doc`
3. `git checkout gh-pages`
4. `git pull origin gh-pages`
5. `rm -rf latest`
6. `cp -r doc/js-data-express/VERSION latest`
7. `cp -r doc/js-data-express/VERSION VERSION`
8. `git add -A`
9. `git commit -m "VERSION"`
10. `git push -u origin gh-pages`

For the docs at js-data.io, you can click the "Suggest Edits" button to submit changes. After your changes are submitted I click a button to merge your changes into the site.

**Comment by crobinson42** [comment]
@jmdobry For some reason the codecov check hung - reason for open/closes :-/

**Comment by crobinson42** [comment]
reopened #21

**Pull request closed without merging**
